CREATE DATABASE RELACION1AN
GO

USE RELACION1AN
GO

CREATE TABLE Equipos (
	IDEquipo INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(50) NOT NULL,
	FechaFundacion DATE NOT NULL, 
	Division CHAR(1) NULL -- Es null si esta desafiliado
)
GO

CREATE TABLE Jugadores (
	Dni BIGINT PRIMARY KEY,
	Apellido VARCHAR(50) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Genero CHAR(1) NULL CHECK ( GENERO = 'F' OR GENERO = 'M' ),
	Mail VARCHAR(50) NULL UNIQUE,
	FechaNac DATE NULL,
	IDEquipo INT NULL FOREIGN KEY REFERENCES Equipos(IDEquipo)
)
GO